//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxING
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            this.Products = new HashSet<Product>();
            this.UserProductGroups = new HashSet<UserProductGroup>();
        }
    
        public int ProductGroupId { get; set; }
        public string ProductGroupName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UserProductGroup> UserProductGroups { get; set; }
    }
}
