//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxING
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.UserProducts = new HashSet<UserProduct>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int ProductGroupId { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<UserProduct> UserProducts { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
    }
}
