//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxING
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduct
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProductGroupId { get; set; }
        public string AccountNumber { get; set; }
        public string DebitCardNumber { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserProductGroup UserProductGroup { get; set; }
    }
}
