//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxING
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProductGroup
    {
        public UserProductGroup()
        {
            this.UserProducts = new HashSet<UserProduct>();
        }
    
        public int UserProductGroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<UserProduct> UserProducts { get; set; }
    }
}
